# Generated by Django 6.0.6 on 2026-06-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('engine', models.CharField(max_length=128)),
                ('data_fundacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('classificacao_indicativa', models.IntegerField()),
                ('tipo', models.CharField(max_length=128)),
                ('genero', models.CharField(max_length=128)),
                ('data_lancamento', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('desenvolvedoras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja_de_jogos.desenvolvedora')),
            ],
        ),
    ]
