# Generated by Django 6.0.6 on 2026-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_de_jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('nome', models.CharField(max_length=128)),
                ('geracao', models.IntegerField(blank=True, null=True)),
                ('ano_lancamento', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Desenvolvedora',
            new_name='Desenvolvedor',
        ),
        migrations.RenameField(
            model_name='jogo',
            old_name='desenvolvedoras',
            new_name='desenvolvedor',
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataforma',
            field=models.ManyToManyField(to='loja_de_jogos.plataforma'),
        ),
    ]
