# Generated by Django 6.0.6 on 2026-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_de_jogos', '0002_plataforma_rename_desenvolvedora_desenvolvedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='tipo',
            new_name='estilo',
        ),
    ]
